name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
    unit-tests:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Validate Gradle Wrapper
          uses: gradle/wrapper-validation-action@v1

        - name: Setup JDK 11
          uses: actions/setup-java@v3
          with:
                distribution: 'zulu'
                java-version: 17

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        - name: Get local.properties from secret
          run: echo "${{secrets.PROPERTY }}" > $GITHUB_WORKSPACE/local.properties

        - name: Run lint
          run: ./gradlew ktlintCheck

        - name: Run lint
          run: ./gradlew lint

        - name: Run unit tests
          run: ./gradlew test

    build:
        runs-on: ubuntu-latest
        needs:
          - unit-tests

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Validate Gradle Wrapper
            uses: gradle/wrapper-validation-action@v1

          - name: Setup JDK 11
            uses: actions/setup-java@v3
            with:
              distribution: 'zulu'
              java-version: 17

          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2

          - name: Get local.properties from secret
            run: echo "${{secrets.PROPERTY }}" > $GITHUB_WORKSPACE/local.properties

          - name: Assemble app
            run: ./gradlew assemble

          - name: Upload build outputs (APKs)
            uses: actions/upload-artifact@v3
            with:
              name: APKs
              path: '**/build/outputs/apk/**/*.apk'
